# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:6.3.0

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --stacktrace --info --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - builds
      - build
      - common/build
      - core/build
      - gateway/build
      - .gradle

test:
  stage: test
  script: gradle --stacktrace --info check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - builds
      - build
      - common/build
      - core/build
      - gateway/build
      - .gradle

merge:
  stage: test
  script: gradle --stacktrace --info check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - builds
      - build
      - common/build
      - core/build
      - gateway/build
      - .gradle
  only:
    - merge_requests

deploy:
  stage: deploy
  script: gradle --stacktrace --info bintrayUpload
  only:
    refs:
      - tags
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - builds
      - build
      - common/build
      - core/build
      - gateway/build
      - .gradle
