blank_issues_enabled: false
contact_links:
  - name: Join the Kord Discord for support!
    url: https://discord.gg/6jcx5ev
    about: If you're looking for support, it's easier to receive the support through our Discord Server. If you're |
      not looking for support, please check for a duplicate of your issue, before opening a report. Thanks!