# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Deployment
on:
  release:
    types: [created]

jobs:
  deloy:

    runs-on: ubuntu-latest
    env:
      KORD_TEST_TOKEN: ${{ secrets.KORD_TEST_TOKEN }}
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

    steps:
      - run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14

      - name: Build with Gradle
        run: gradle --stacktrace --info bintrayUpload
