# This workflow will build and deploy docs to GitHub Pages whenever something is pushed to 0.8.x

name: Docs

on:
  push:
    branches:
      - 0.8.x

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    env:
      GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
      GITHUB_BRANCH_NAME: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build docs with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info dokkaHtmlMultiModule
      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/htmlMultiModule
          branch: gh-pages
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          commit-message: Update docs
